name: Cancel previous workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ toJSON(github.event) }}

    - uses: spaceface777/cancel-workflow-action@main
      with:
        workflow_id: ${{ github.event.workflow.id }}
