name: Cancel previous workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ github.event.workflow_run.head_repository.full_name }} ${{ github.event.workflow_run.head_branch }}'

    - uses: spaceface777/cancel-workflow-action@main
      if: ${{ github.event.workflow_run.head_repository.full_name != 'spaceface777/cancel-workflow-action-test' || github.event.workflow_run.head_branch != 'main' }}
      with:
        workflow_id: ${{ github.event.workflow.id }}
