name: Cancel previous workflows

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
