name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          workflow_id: 11604946 # get this from https://api.github.com/repos/:org/:repo/actions/workflows - can be a comma-separated list of workflow IDs
          access_token: ${{ github.token }}


  job_1:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for one minute
        run: sleep 60

  job_2:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 2 minutes
        run: sleep 120

  job_3:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 5 minutes
        run: sleep 300
  
  job_4:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600

  job_5:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600
  
  job_6:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600
  
  job_7:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600
  
  job_8:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 15 minutes
        run: sleep 900

  job_9:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 15 minutes
        run: sleep 900

  job_10:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 15 minutes
        run: sleep 900

  job_11:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 20 minutes
        run: sleep 1200

  job_12:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 20 minutes
        run: sleep 1200

  job_13:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 20 minutes
        run: sleep 1200
  
  job_14:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 30 minutes
        run: sleep 1800

  job_15:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 30 minutes
        run: sleep 1800
