name: Long CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: wait 30 seconds before scheduling all jobs (to allow them to be cancelled)
        run: sleep 30

  job_1:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for one minute
        run: sleep 60

  job_2:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 2 minutes
        run: sleep 120

  job_3:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 5 minutes
        run: sleep 300
  
  job_4:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600

  job_5:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 10 minutes
        run: sleep 600

  job_6:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 15 minutes
        run: sleep 900

  job_6:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 20 minutes
        run: sleep 1200

  job_7:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 30 minutes
        run: sleep 1800

  job_8:
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: do nothing for 30 minutes
        run: sleep 1800
